name: Ubuntu 22.04

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ubuntu-build:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        shared: [ON, OFF]
        cxx: [g++-12, clang++-14]
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Setup Ninja
        run: sudo apt-get install ninja-build
      - name: Prepare
        run: cmake -D ADA_BENCHMARKS=ON -DBUILD_SHARED_LIBS=${{matrix.shared}} -G Ninja -B build
        env:
          CXX: ${{matrix.cxx}}
      - name: Build
        run: cmake --build build -j=2
      - name: Test
        run: ctest --output-on-failure --test-dir build
      - name: Run default benchmark
        run: cd build && benchmarks/bench
      - name: Prepare-No-Dispatch
        run: cmake -D ADA_BENCHMARKS=ON -DBUILD_SHARED_LIBS=${{matrix.shared}} -G Ninja -B build -D ADA_NO_DISPATCH=ON
        env:
          CXX: ${{matrix.cxx}}
      - name: Build-No-Dispatch
        run: cmake --build build -j=2
      - name: Test-No-Dispatch
        run: ctest --output-on-failure --test-dir build
      - name: Run default benchmark-No-Dispatch
        run: cd build && benchmarks/bench